### PR TITLE
GRECLIPSE-1803 Fix for very old Groovy to prevent NoClassDefFoundError

### PR DESCRIPTION
**Pull request by DenisMurashev**

### CODE REVIEW

**Comment by guilhermefaleixo** [comment]
Hello,
I was trying to solve this problem, because I am running the GGTS 3.6.4 with groovy compiler 1.8.6 and grails 2.1.1 and I am getting this error when i try to run as Junit test. but I don't fully understood your commit, could you help me ??

kind regards,
Guilherme

**Comment by pivotal-issuemaster** [comment]
@DenisMurashev Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=groovy/groovy-eclipse&pullRequestId=102) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by DenisMurashev** [comment]
Groovy 1.8 doesn't support static type checking.
So it's just doing nothing stub class for Groovy 1.8 to prevent the error.

**Comment by pivotal-issuemaster** [comment]
@DenisMurashev Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=groovy/groovy-eclipse&pullRequestId=102)!

**Pull request closed without merging**
