### PR TITLE
GROOVY-ECLIPSE Issue 162: Add all output folders of dependent projects

### PR DESCRIPTION
**Pull request by hennito**
This fixes the issue 162 for me. 
I must admit though that I am not an eclipse expert, I don't know if the output folders of dependent projects need to be handled somehow (replace variables and the like).

I also don't know since which version of eclipse it is possible to assign separate output folders to source folders.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@hennito Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=groovy/groovy-eclipse&pullRequestId=163) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by hennito** [comment]
Done.

**Comment by pivotal-issuemaster** [comment]
@hennito Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=groovy/groovy-eclipse&pullRequestId=163)!

**Comment by eric-milles** [comment]
@hennito We have many projects with this sort of structure -- main code to one output directory and test code output to another.  I have not seen this problem with our inter-project dependencies.  I'll have a look at your example and see what I can see.

**Comment by hennito** [comment]
@eric-milles thanks for checking on this.

we have multi project like
* core
* tracking

Each of the projects has 
src/common
src/server
src/client
src/test

tracking/src/common depends on core/src/common
tracking/src/test depends on tracking/src/{client, server, common}
and on core/src/{client, server, common, test}

**Comment by hennito** [comment]
Closing this PR. Solution provided  here
https://github.com/groovy/groovy-eclipse/issues/162

Thanks a lot @eric-milles !

**Pull request closed without merging**
