### PR TITLE
GRECLIPSE-1822 Rename source files in order that JDT can find them by default

### PR DESCRIPTION
**Pull request by apupier**

### CODE REVIEW

**Comment by apupier** [comment]
CLA signed on https://support.springsource.com/spring_eclipsecla_committer_signup

**Comment by apupier** [comment]
no news on this PR?

**Comment by apupier** [comment]
Up, migrating to a groovy version 2.x and we will unfortunately have to patch the plugin. Any chance to integrate these changes in order to avoid avoid to patching the plugin when we will upgrade our Target Platform? Do I need to do something else?

**Comment by pivotal-issuemaster** [comment]
@apupier Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=groovy/groovy-eclipse&pullRequestId=110) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by aclement** [comment]
Believe superceded by https://github.com/groovy/groovy-eclipse/pull/199 which is going in imminently.

**Pull request closed without merging**
