### PR TITLE
Neon SR1 plus minor clean-ups

### PR DESCRIPTION
**Pull request by eric-milles**
Courtesy of @felixdo, here is the JDT Core 3.12.1 patch.  I also replaced some of the patched parts of JDT with stock ones where possible.  I do have a replacement for semantic highlighting as well, but it is a bit more involved.

### CODE REVIEW

**Comment by aclement** [comment]
If it is based on work by @felixdo - has he signed the CLA?

**Comment by eric-milles** [comment]
The IP really belongs to Eclipse.org; it is Neon SR1 applied to the jdt-patch project.

**Comment by aclement** [comment]
Hey Eric, I understand what it is - but it still feels a slightly gray area to me. When I apply those updates myself it feels completely clean. I'm just trying to work through and make sure I'm happy with the process we are using here. I know it should just be the changes that bring JDT up to date but I don't know the full history of them - is there anything in there that shouldn't be? Who is on the hook if there is? At the moment it would be you as the CLA signee that submitted them I suspect.  So how did you transfer them from felixdo into this commit.

**Comment by eric-milles** [comment]
Is it possible to merge the latter two commits at least?  Or would I need to rebase them somehow?

As for the JDT core patch, I just diffed the current e46 against the 4.6 maintenance branch that has the patches applied (https://github.com/felixdo/eclipse.jdt.core/tree/R4_6_maintenance/org.eclipse.jdt.core).  I have been running with these changes for some time now.  I had been waiting for these to be pulled in, but thought I would take the initiative since there were recent issues caused by running without the changes.

**Comment by aclement** [comment]
We need to work out the best way to keep these things in step (concerning the jdt chasing). I certainly have no plans to update JDT myself so I believe what felixdo is doing is the right way, I'm just not totally clear of the simplest setup.

**Comment by aclement** [comment]
Having felixdo periodically submit PRs for the diff between that and this project doesn't seem ideal either (but would work). Building that project separately and publishing to a consolidated update site alongside the rest of the groovy-eclipse from this project - that could work but the IP trail of the product as a whole becomes a bit strange. Using a git submodule reference in groovy-eclipse to a jdtcore fork like felixdos but under the same groovy org, maybe.

**Pull request closed without merging**
