### PR TITLE
fixed "StringIndexOutOfBoundsException: begin 0, end -1, length 0"

### PR DESCRIPTION
**Pull request by mojo2012**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@mojo2012 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=groovy/groovy-eclipse&pullRequestId=984)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=groovy/groovy-eclipse&pullRequestId=984) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@mojo2012 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=groovy/groovy-eclipse&pullRequestId=984)!

**Comment by eric-milles** [comment]
Can you share the static favorites config that you are using?  I'd like to create a test case for this before making any code changes.

**Comment by mojo2012** [comment]
Just check out https://github.com/mojo2012/groovier. Open the SqlTest.groovy file and position the cursor at (1):

```groovy
@Test
	void testCreateSql() {
		def show = { println it }
		def square_root = { double it -> Math.sqrt(it) }

		Sql.select "a", "b" \
			(1) from "table" \
			execute()
	}
```

Then hit ctrl-space, booom

**Comment by eric-milles** [comment]
I need to know what is present in favoriteStaticMembers.  This is populated from _Window > Preferences > Java > Editor > Content Assist > Favorites_

image

**Comment by mojo2012** [comment]
Damn, there was an empty value in the list! I removed it and now it works. I have no idea how it got into there, it's not possible to add it manually.
But I can add a member value `a` which causes the same exception!
Bildschirmfoto 2019-11-03 um 19 08 41

**Comment by eric-milles** [comment]
Thanks.  I'll add tests for those cases and incorporate your fix.

**Pull request closed without merging**
