### PR TITLE
Support boolean value annotations

### PR DESCRIPTION
**Pull request by astral303**
This fixes the error where, currently, when referencing annotations with boolean values, the compiler crashes with:

```General error during canonicalization: NYI for signature Z

org.codehaus.jdt.groovy.internal.compiler.ast.GroovyEclipseBug: NYI for signature Z
	at org.codehaus.jdt.groovy.internal.compiler.ast.JDTAnnotationNode.createExpressionFor(JDTAnnotationNode.java:157)
	at org.codehaus.jdt.groovy.internal.compiler.ast.JDTAnnotationNode.ensureMembersInitialized(JDTAnnotationNode.java:114)
	at org.codehaus.jdt.groovy.internal.compiler.ast.JDTAnnotationNode.getMembers(JDTAnnotationNode.java:74)
	at org.codehaus.groovy.ast.tools.GeneralUtils.hasClosureMember(GeneralUtils.java:444)
	at org.codehaus.groovy.ast.tools.GeneralUtils.copyAnnotatedNodeAnnotations(GeneralUtils.java:243)
	at org.codehaus.groovy.transform.trait.TraitComposer.createForwarderMethod(TraitComposer.java:361)
	at org.codehaus.groovy.transform.trait.TraitComposer.applyTrait(TraitComposer.java:176)
	at org.codehaus.groovy.transform.trait.TraitComposer.doExtendTraits(TraitComposer.java:111)
	at org.codehaus.groovy.control.CompilationUnit$11.call(CompilationUnit.java:215)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1139)```

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@astral303 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=groovy/groovy-eclipse&pullRequestId=887)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=groovy/groovy-eclipse&pullRequestId=887) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@astral303 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=groovy/groovy-eclipse&pullRequestId=887)!

**Comment by eric-milles** [comment]
Thanks for the submission.  I reworked your changes a bit to support all primitive types.

**Comment by eric-milles** [comment]
https://bintray.com/groovy/maven/groovy-eclipse-batch/2.4.17-02

Testing it some more locally before publishing and synching with Maven Central.

**Pull request closed without merging**
