### PR TITLE
https://github.com/groovy/groovy-eclipse/issues/600

### PR DESCRIPTION
**Pull request by ybayk**
testAssignedVariable10 fails before the fix and passes after.

### CODE REVIEW

**Comment by eric-milles** [comment]
Should the recovery exist for all forms of assignment?  For example, `foo += |`

**Comment by eric-milles** [comment]
I forgot to note that grammar changes are not re-built by the maven build.  The changes to the recognizer, etc. must be included with the commit.

I have a commit coming in a couple minutes to fix this and add recovery for `+=`, etc. and to add error recovery tests.

**Comment by ybayk** [comment]
sorry, intentionally left other ops untreated as it was no use in AssignedVariable point-cut
also not clear what to do for antlr 4

**Comment by eric-milles** [comment]
I have not applied any parser recovery to the Antlr4 grammar or plug-in.  I made a couple attempts but have no working strategy at the moment.

**Pull request merged**
