### PR TITLE
[190] Initial Oomph setup model for groovy eclipse

### PR DESCRIPTION
**Pull request by felixdo**
In case you have no clue what Oomph is, it is an eclipse tool that can automatically provision eclipse-based development environments based on a model description. This file here is the model description to setup a development environment for Groovy Eclipse. When the user selects it in the eclipse installer, this:

- Installs one of the available Eclipse IDE Packages + Groovy Eclipse.
- Clone the groovy eclipse repo, the user can select between anonymous and read-write access.
- Import the groovy eclipse source code from the clone location. During setup, the user decides which target platform to use (I added support for Neon and Oxygen), so that the correct jdt patch is imported automatically.
- Organizes the source code into a few working sets.
- Disable "Add dsld support to all groovy projects"

It would be awesome if this could be merged. We could then request the setup to be referenced in Oomphs main project catalog, so that the installer would include Groovy Eclipse as a provisionable open source project. Once that is done, I would update the developer wiki docs. 

You can of course try this out first, too: Just [download the installer](https://wiki.eclipse.org/Eclipse_Installer) and the [GroovyEclipse.setup](https://raw.githubusercontent.com/felixdo/groovy-eclipse/master/GroovyEclipse.setup) file and follow these [instructions](https://wiki.eclipse.org/Eclipse_Oomph_Authoring#Testing_the_Setup_Model 
)

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@felixdo Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=groovy/groovy-eclipse&pullRequestId=295)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=groovy/groovy-eclipse&pullRequestId=295) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by felixdo** [comment]
Hey I signed the CLA but the check still fails?

**Comment by pivotal-issuemaster** [comment]
@felixdo Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=groovy/groovy-eclipse&pullRequestId=295)!

**Comment by eric-milles** [comment]
Can you add a screenshot to this request that shows what a workspace looks like (incl. the Installation Details dialog) after the steps are completed?  I'm trying to get a feel for you working sets in Package Explorer and installed features without having to run through it all.

**Comment by felixdo** [comment]
Yes, please look at http://imgur.com/a/jwJEo

* I can't get around having the user to select groovy 2.1 compiler and clean/rebuild manually. I tried to automate setting the compiler version, but groovy-eclipse doesn't register that change until a restart + manual clean is still required, so I figure having to set it manually is less annoying actually. But I wonder what happens if I deselect "Warn different project + workspace compiler versions"?

* I read that only one org.codehaus.groovyXX project should be open at any time, so the user has to close the unwanted versions by hand. Alternatively I can ask the user which version is wanted and only import that specific plugin+feature. Would that be better? I don't know how often one would switch between different groovy versions..

**Comment by eric-milles** [comment]
Thanks for the screenshots.  You don't need to install all Groovy Compiler versions into your Eclipse to develop for Groovy Eclipse.  Only 2.1 is required and if it were the only version available, it would remove the need to have the user set it and restart.  Here are the minimal plug-ins for a viable development environment:

groovy-eclipse-devel

You may have any number of org.codehaus.groovyXX projects open.  The latest one will be used by tests and Eclipse Application runs.  You may not have more than one org.eclipse.jdt.core project open.  And the one you have needs to match your Target Platform.

As for the working sets, I group the projects quite similarly (see below).  Although I don't bother with the feature projects in my Package Explorer view since they are not compiled or used when running tests or an Eclipse application.  One note, org.codehaus.groovy.eclipse is a branding plug-in and so I group it with the feature plug-ins.

groovy-eclipse worksets

**Comment by felixdo** [comment]
* I don't think it is possible to install just 2.1, because the the groovy eclipse feature includes 2.3 and 2.4.
* I will make the working sets so that they match your screenshot
* What is installed depends also on what "Product" the user selects on the initial wizard page:
product-page

 I don't install anything on top of that besides Groovy Eclipse, so the result is just the selected product + groovy eclipse. In my screenshot it is the contents of the Eclipse Committers product + Groovy Eclipse.

(Note that in Oomph there is a special user.setup file that is 'merged' into all your installations, so that you can have extra stuff installed across all your oomph based IDEs, e.g. if you'd always want the vim plugin, you would add it to your user.setup and oomph would make sure it is always installed..)

**Comment by eric-milles** [comment]
Are you assuming the installation of the Eclipse Commiters package?  Otherwise, you'd need to ensure the Execution Environment Descriptors and the Plug-in Developer Resources.

**Comment by felixdo** [comment]
Oh no. You can pick anything suitable on that page, the Execution environment descriptors will be installed together on top of that. (So I actually lied when I said that I only install groovy eclipse, it is groovy eclipse + these descriptors):
ee-descriptors

Oh and btw. If you agree to merge, I'd need to make one small modification: In the bottom of the screenshot you'll see that I still refer to the raw content of the file in my groovy-eclipse clone. I would change that to groovy/groovy-eclipse before you pull.

**Comment by felixdo** [comment]
Ok I amended my initial commit to have make the workingsets look like yours. I can't however hide the "Features" working set automatically, so the user will have to do that manually. I can't also get around having to set groovy 2.1 manually + running a manual clean/build after the forced restart. Right now it is close to as good as it gets; The only thing I would need to do is to fix the oomph redirection value to the felixdo/groovy-eclipse repo.

**Comment by eric-milles** [comment]
Could you get one volunteer to start with a bare machine and run your steps?  I'd like to know if that person could run Build All and then run AllGroovyTests as a plug-in test.

Re the compiler setting, I think that is just a preference value in .metadata\.plugins\org.eclipse.core.runtime\.settings\org.codehaus.groovy.eclipse.compilerResolver.prefs
  groovy.compiler.level=21

**Comment by felixdo** [comment]
I don't know.. Do you know any groovy-eclipse developers? :p I can make a video if you want so you can follow. However, I will have to add a small step which won't be necessary later when the setup is added to oomphs project catalog.

I am sure that the groovy compiler is "just" a preference. The thing is, that if you change that preference via the Groovy Compiler Preferences Page, this will ask for a restart, and if you modify it through API, no restart will happen. I also saw that a restart alone isn't enough. You have to change the pref, restart, and make a clean build.

**Comment by eric-milles** [comment]
I just want to be sure the steps are complete and can be executed by someone besides yourself or myself -- someone without deep knowledge of how to setup one of these worksapces.

Also, it may be better to have only one Groovy runtime project open at a time.  I just remembered that I have seen dependent plug-ins refer not to the latest one all the time.  Not sure if it is possible to import the project but have it closed initially.

**Comment by felixdo** [comment]
No I can't close the projects automatically. But I could add a choice so that the user defines which version is imported initially, and only import that one.

As for testing, I could post to the groovy-user list and we'll see if someone wants to test.

**Comment by felixdo** [comment]
Eric, would you prefer to import all groovyXX runtime projects and close all but one? Or should I just import a specific one? In your screenshot, all are open..

**Comment by felixdo** [comment]
I have added some rudimental [documentation](https://github.com/felixdo/groovy-eclipse/blob/master/docs/AutomaticSetupWithOomph.md)

 Could you fly over it and see if anything is totally wrong? I'm still unsure to which groovy runtime project should be open. Do all tests need to pass with all groovy versions?

I would then post this to groovy-user and we'll see if this awakens some interest.

**Comment by eric-milles** [comment]
Yes, if possible import all org.codehaus.groovyXX but close all except the latest.  There is 1 test that will generate a failure if the latest Groovy is not used.  Each of the others should work but the 1 test failure will be produced for sure.

Docs look good.  Will it be possible to show up as just "Groovy" in the catalog once finalized?  Is it possible to incorporate the instructions into the existing setup guide?  I am thinking your directions would go at the start and would replace some of the setup steps in the current guide.

**Comment by eric-milles** [comment]
Also, there are DSL and SDK features.  I'm not sure if they made it into your list.  The hierarchy of features is quite confusing to me.  I plan on removing a couple levels for 3.0.

**Comment by eric-milles** [comment]
One addition you could make to the test section.  Instead of running alltests, you can run GroovyJDTTests (with "Run in UI thread" unchecked") and AllGroovyTests separately.  When making strictly UI changes, you would only need to run the latter.

**Comment by felixdo** [comment]
* I saw the dsl/sdk features. Not sure what they are used for, you can always import these manually later if needed. I like the sdk feature idea, but it looks like it hasn't been updated for some time.

* We would definitely put the setup instructions on top of the old 'manual' instructions, but that would be a follow up commit. (I will have to update the docs anyways as soon as the oomph maintainers have added groovy-eclipse to the main catalog).

* I don't know if just "Groovy" is good.. People would probably think that this is for groovy core development? Catalog maintainers won't probably like it either..

**Comment by eric-milles** [comment]
None of the other projects in the screenshot included Eclipse in their name.  How does JDT appear?

**Comment by felixdo** [comment]
We should stick to the github project name.

**Comment by eric-milles** [comment]
Wouldn't that be "Groovy-Eclipse" then?

**Comment by felixdo** [comment]
I'm okay with Groovy-Eclipse.

**Comment by eric-milles** [comment]
Besides that, we are able to make updates to the .setup file to correct any problems we find, correct?  That is, there are no semi-permanent decisions left.  If so, I'm fine with accepting the merge request when you're ready.

**Comment by felixdo** [comment]
Yes potential problems can be fixed later. And new features can be added too, for example we could impose new/additional preferences, such as coding style and formatter later. The setup engine will automatically fetch updates from our model and apply these updates to existing installs.

I am not 100% sure, but I think the location of the .setup file in the repo should not change after it's been added to the catalog. Are you okay with the root folder?

**Comment by eric-milles** [comment]
Yes, it makes sense to me to have this file in the root of the project.  Can it be named "groovy-eclipse.setup"?

**Comment by felixdo** [comment]
Ok I'll rename the file to groovy-eclipse.setup and the project to Groovy-Eclipse, and update the screenshots in the documentation which is the worst part.. :)

**Comment by felixdo** [comment]
One maybe important question: Should I require presence of a jre7? At the moment the installer will ask for java 8 only.

**Comment by eric-milles** [comment]
That's a complicated question actually.  The projects have requirements all the way back to Java 5 -- and some of the very old org.eclipse.jdt.core projects require Java 4.  You can get by without the real deal, but there is a chance for using APIs that are not available on a Java 5 JRE for example.  When I first started working with G-E, I had to fix some non-compliant Java 5 stuff for it to compile with a real Java 5.

For basic development against latest Eclipse and Groovy, Java 8 is quite sufficient.  And I think it will be the minimum for G-E 3.0.

**Comment by felixdo** [comment]
I get 36 Errors and 1 Failure for GroovyAllTests. The errors are all in DSLContentAssistTests and DSLNamedArgContentAssistTests and have all the same trace:

Java Model Exception: Java Model Status [Build path contains duplicate entry: 'GROOVY_DSL_SUPPORT' for project 'TestProject']
	at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:786)
	at org.eclipse.jdt.internal.core.JavaProject.setRawClasspath(JavaProject.java:3102)
	at org.eclipse.jdt.internal.core.JavaProject.setRawClasspath(JavaProject.java:3064)
	at org.eclipse.jdt.internal.core.JavaProject.setRawClasspath(JavaProject.java:3117)
	at org.codehaus.groovy.eclipse.test.TestProject.addClasspathEntry(TestProject.java:165)
	at org.codehaus.groovy.eclipse.test.TestProject$addClasspathEntry$4.call(Unknown Source)
	at org.codehaus.groovy.eclipse.test.GroovyEclipseTestSuite.addClasspathContainer(GroovyEclipseTestSuite.groovy:164)

The failure is also in the dsl suite for testDSLProposalFirstStaticField:

java.lang.AssertionError: Proposal 'instance' should have preceded proposal 'aaa' in: 
aaa : Object - Foo (1000)
annotatedInterfaces : AnnotatedType[] - Class (1000)
annotatedSuperclass : AnnotatedType - Class (1000)
annotationData : Class$AnnotationData - Class (1000)
annotationType : AnnotationType - Class (1000)
annotations : Annotation[] - Class (1000)
cachedConstructor : Constructor - Class (1000)
canonicalName : String - Class (1000)
classLoader : ClassLoader - Class (1000)
classLoader0 : ClassLoader - Class (1000)
classRedefinedCount : int - Class (1000)
[..]

Any clues?

**Comment by felixdo** [comment]
The error occurs because "Automatically add DSL support to all Groovy projects" is true and GroovyDSLContentAssistTests.setup() calls addClasspathContainer(GroovyDSLCoreActivator.CLASSPATH_CONTAINER_ID) so these two collide.

Can you tell me how you are avoiding this without fixing code? Do you run a customized/prepared test workspace which has auto-add support off?

**Comment by felixdo** [comment]
Okay, I see. On the build.spring.io server, tests are run with -Dgreclipse.dsld.disabled=true which ultimately causes these tests to be skipped. So, I give a go for merge, or do you want me to rebase first?

**Comment by felixdo** [comment]
Thank you. I have now created https://bugs.eclipse.org/bugs/show_bug.cgi?id=517092 for inclusion in the project catalog. Once that is done I can update/simplify the documentation here.

**Pull request merged**
