### PR TITLE
Now you can use @formatter tag for to ignore the formatter.

### PR DESCRIPTION
**Pull request by aya-eiya**

### CODE REVIEW

**Comment by aya-eiya** [comment]
I'm sorry to keep you waiting.

>>Put the //@formatter:on line back, make the same selection and format it. Semi-colons are removed,but they were meant to stay i suppose because of the //@formatter:off above the class. Hope, I understood eclipse's //@formatter:off/on markers correctly, so please correct me I'm wrong.

>There is something I'm not too happy about with this fix... There is a MalformedTreeException generated when the code snippet i pasted is being formatted
>(ensure "remove unnecessary semicolons preference is on as I mentioned):

I didn't understand what you are meaning.now I know what is the problem.
The exception is threw in case of the "remove unnecessary semicolons" setting is on.

>It might be OK due to the comment in GroovyBeautifier#addEdit(...) that catches the exception above.
>However, I wonder if we could make that fix a bit better by initializing the global ignore tokens in DefaultGroovyFormatter#format() using your FomatterOffHandler, but instead of the MultiTextEdit just get a set of tokens that should be ignored... Then pass these ignored token to GroovyIndentation and GroovyBeautifier and then consider that global tokens ignore list when processing tokens.

Actually I don't like to add something to the global scope, but the merits you mentioned looks good.
I'll try your way.

**Comment by pivotal-issuemaster** [comment]
@aya-eiya Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=groovy/groovy-eclipse&pullRequestId=109) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by satishgudluru** [comment]
This comment is not related to the pull request.
Looks like this compiler is not supporting java8. Getting the following error.
**BUG! exception in phase 'class generation' in source unit '/Users/xxxxx/a/b/c/Test.groovy' unsupported Target TYPE_USE.
at org.codehaus.groovy.vmplugin.v5.Java5.getElementCode(Java5.java:371)**

If the Test.groovy uses @NotNull annotation t throws this error.
is there any way we can update the groovy version in this compiler plugin so that we can build

**Comment by eric-milles** [comment]
Are you compiling from Eclipse or Maven?  What versions of Groovy-Eclipse artifacts are you using?  For your project, how are you specifying Java 8?

The compiler should be Java 8 and 9 compatible.

Can you open a separate issue for this?

**Comment by satishgudluru** [comment]
@eric-milles I have opened a new issue for the issue I mentioned above. BUG! exception in phase 'class generation' in source unit '/Users/xxxxx/a/b/c/Test.groovy' unsupported Target TYPE_USE.

https://github.com/groovy/groovy-eclipse/issues/425

@Others,  This is not related to this pull request., please ignore this comment.

**Pull request closed without merging**
